const errorCreateTaskMock ={
  newId: 1,
  title: 'lorem ipsum lorem ipsum lorem',
  status: 'pronto',
  description: `loremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum
loremipsumloremipsumloremipsumloremipsumloremipsumloremipsumloremipsum`,
};

module.exports = errorCreateTaskMock;
